repos:
  - repo: local
    hooks:
      - id: run-pytest
        name: Run pytest
        entry: pytest
        args: ["--ignore=app/alembic"]
        language: system
        types: [python]
        stages: [pre-commit, pre-push]

